[general]
static=yes
writeprotect=no

[globals]
CONSOLE=Console/dsp
IAXINFO=guest
TRUNK=IAX2/your-voip-carrier

[default]
exten => s,1,NoOp(Default context)
 same => n,Hangup()

[vicidial]
exten => _X.,1,NoOp(Vicidial dial request ${EXTEN})
 same => n,Hangup()

[from-internal]
include => vicidial
exten => _9.,1,NoOp(Agent extension ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN})
 same => n,Hangup()
