[general]
context=default
allowguest=no
udpbindaddr=0.0.0.0:5060
tcpenable=yes
tcpbindaddr=0.0.0.0:5060
srvlookup=yes
disallow=all
allow=ulaw
allow=alaw

[1001]
type=friend
secret=VicidialLegacyPhone1001!RotateMe
host=dynamic
context=from-internal
canreinvite=no
nat=force_rport,comedia
